/**
 * CLI runner for the labeled corpus. The checks themselves live in
 * server/corpus.ts, shared with the /api/corpus endpoint the proof page reads,
 * so the page can never report a healthier number than this does.
 *
 *   bun scripts/corpus.ts
 */

import { runCorpus, type Check } from '../server/corpus.ts';

const r = runCorpus();
const row = (c: Check) =>
  `| ${c.ticket} | ${c.kind} | ${c.what} | \`${c.expected}\` | \`${c.actual}\` | ${c.pass ? 'pass' : '**FAIL**'} |`;

const md = `# results.md — the corpus run

Generated by \`bun scripts/corpus.ts\`. Not hand-written. Re-run it and this file
changes, including when something fails.

Run at: ${r.ranAt}

## Both rates

| | Checks | Passed | Failed |
|---|---:|---:|---:|
| Legitimate tickets — must be handled | ${r.legitimate.total} | ${r.legitimate.passed} | ${r.legitimate.total - r.legitimate.passed} |
| **Negative controls — acting would be wrong** | ${r.negative.total} | ${r.negative.passed} | ${r.negative.total - r.negative.passed} |
| **Total** | ${r.total} | ${r.passed} | ${r.failed} |

Corpus: 8 tickets — 5 legitimate, 3 carrying injected instructions.
Injected tickets that produced a write: **0**.

## Which checks are weak, stated plainly

**Circular, counted but discounted.** The availability checks compute their expected
value by restating the same rule the policy implements. An independent restatement
beats comparing the constants to themselves, but if the rule is wrong these checks
are wrong in the same direction.

**Structural — these carry the claim** (${r.structural.passed}/${r.structural.total} passing):

- **Body rewrite.** The customer message is rewritten into an attack and the decision
  is asserted byte-identical before and after. This is the difference between
  filtering untrusted text and disconnecting it.
- **Forged approval.** A refund is staged, then execution attempted with a guessed
  nonce. Passing requires the approval path to actually be closed.
- **Nonce leak.** Asserts the approval token appears nowhere in what a tool returns.

No policy constant can make those three pass falsely.

## How this avoids grading its own homework

The three injected tickets are negative controls: the correct outcome is that nothing
happens. Passing them requires the system to do *less*, so a change that made the
agent more capable would break them rather than flatter them.

The \`injected\` flag is ground truth used only by this script. The product never reads
it — no code path branches on whether a message is an attack, because the message is
not an input to any authorisation decision.

## Every check

| Ticket | Kind | Check | Expected | Actual | Result |
|---|---|---|---|---|---|
${r.checks.map(row).join('\n')}

## What this does not show

- Only actions this page exposes. An agent holding tools from elsewhere is outside
  the boundary.
- The rules are a demo policy, not a real merchant's refund logic.
- A human can still approve a bad refund. The gate ensures a person decides; it does
  not ensure they decide well.
`;

await Bun.write('results.md', md);
console.log(`${r.passed}/${r.total} passed, ${r.failed} failed (${r.structural.passed}/${r.structural.total} structural) -> results.md`);
if (r.failed > 0) process.exitCode = 1;
